config/routes.rb
Rails.application.routes.draw do

 

  resources :pictures
  

  root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  scope :most_recent, -> { order(created_at: :desc) }
  scope :most_recent_three, -> {most_recent.limit(3) }
  scope :most_recent_five, -> {most_recent.limit(5) }
  scope :created_before, ->(time) {where("created_at < ?", time)}

  # paginates(:per_page => 3)


  @@items_per_page = 3

  def self.items_per_page
    @@items_per_page
  end

  def self.page number
    items_per_page = @@items_per_page
    offset = (items_per_page * number.to_i) - items_per_page
    order(created_at: :desc).limit(items_per_page).offset(offset)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @page = params[:page] ? params[:page].to_i : 1
    @most_recent_pictures = Picture.page(@page)
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    
    if @picture.update_attributes(picture_params)
      redirect_to picture_path(@picture)
    else
      render :edit
    end
  end

  def destroy
    # @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_url
  end

private

    def picture_params

      params.require(:picture).permit(:artist, :title, :url)

    end

    def set_picture
      @picture = Picture.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def paginate(things)
    # content_tag(:ul) do
    page = link_to("Previous Page", pictures_path({:page => (@page-1) }))
    page += " | "
    page += link_to("Next Page", pictures_path({:page => (@page+1) }))
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>

  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>

  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  
<% end %>

app/views/pictures/edit.html.erb
<h1>Edit a Picture</h1>
<p> <%= link_to "Back to picture", @picture %> </p>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>Pictures</h1>
<%= link_to "New picture", new_picture_path %><br>
<%= paginate(@most_recent_pictures) %>

<% @most_recent_pictures.each do |picture| %>
  <p><%= picture.title %>, <%= picture.artist %></p>
  <%= link_to image_tag(picture.url),  picture_url(picture) %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a Picture</h1>
<%= link_to "Back to pictures", pictures_url %>

<%= render 'form' %>

  

app/views/pictures/new_test.html.erb
<h1>Day 3 Forms</h1>
<!-- html_tag -->

<!-- form_tag -->

<!-- form_for -->

<%= form_for Picture.new do |f| %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :url %>
  <%= f.text_field :url %>
  
  <%= f.submit "Save" %>  
<% end %>
  

app/views/pictures/show.html.erb
<h1>Picture</h1>
<%= link_to "Back to Pictures", pictures_url %> | 
<%= link_to "Edit", edit_picture_path(@picture) %> |
<%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"} %>
<p><%= @picture.title %>, <%= @picture.artist %></p>
<%= image_tag @picture.url %>